### ISSUE TITLE
Not available in the Central Repo

### ISSUE THREAD

**Issue by atehrani** [launchdarkly/api-client-java#1]
When do we expect to have this client library available in the central repo?

`Could not find artifact com.launchdarkly:api-client-java:jar:1.0.0 in central (https://repo.maven.apache.org/maven2)`

**Comment by jkodumal** [comment]
Hi @atehrani -- Thanks! We're working on it. It'll likely take us a few days to get this approved and into Maven Central.

**Comment by pknepali** [comment]
Hi, Do you have ETA on when this will be done? It would help lot if this is available ASAP.
Thanks.

**Comment by jkodumal** [comment]
Hi @pknepali,

We're hoping to have this out in the next day or so. We actually published the artifact today, but there was a slight miscommunication and we published under the wrong artifact name. I'll reach out when we've squared that away.

**Comment by atehrani** [comment]
Are these the correct Maven coordinates?

> <dependency>
    <groupId>com.launchdarkly</groupId>
    <artifactId>api-client</artifactId>
    <version>1.0.2</version>
</dependency>

**Comment by jkodumal** [comment]
@atehrani That's correct-- please let me know if you run into any issues using that artifact.
