### ISSUE TITLE
FeatureFlagConfig should implement Comparator

### ISSUE THREAD

**Issue by atehrani** [launchdarkly/api-client-java#3]
The FeatureFlagConfig class should implement different Comparators. It would be nice to be able to sort them by name/environment/on/...etc.

**Comment by bwoskow-ld** [comment]
Hi @atehrani,

Given that `api-client-java` is auto-generated from our OpenAPI spec, we're unlikely to be able to implement this. To my knowledge there isn't a way specify that models should implement various Java interfaces.

However, if you're after comparing flags across environments, see [my response](https://github.com/launchdarkly/api-client-java/issues/4#issuecomment-548040823) on your other issue.
