### ISSUE TITLE
Latest version in Maven Central is 3.1.0

### ISSUE THREAD

**Issue by javydreamercsw** [launchdarkly/api-client-java#6]
Noticed the latest is 3.5.0 but I can't find the artifact anywhere.

**Comment by bwoskow-ld** [comment]
Hi @javydreamercsw ,

We're aware of this issue and have it on our backlog.

_Tracked internally as 65679._

**Comment by bwoskow-ld** [comment]
Hi @javydreamercsw ,

Thanks for reporting this and for your patience while we looked into it. New versions of the Java API client will be published to Maven Central from now on.
